version: '3'
services:
  mongodb:
    image: mongo:3.4-jessie
    container_name: "mongodb"
    network_mode: host
    ports:
      - "27017:27017"
    expose:
      - 27017

  eureka-service:
    build: ./eureka-service
    restart: always
    network_mode: host
    container_name: eureka
    ports:
      - "9091:9091"
    expose:
      - 9091

#  config-service:
#    build: ./spring-config-server
#    restart:  always
#    depends_on:
#      - mongodb
#    container_name: config
#    ports:
#      - "8888:8888"
#    expose:
#      - 8888
  config-server:
    build: ./spring-config-server
    restart: always
    network_mode: host
    container_name: config
    ports:
      - "8888:8888"
    expose:
      - 8888

#  track-service:
#    build: ./track-service
#    restart:  always
#    container_name: track
#    depends_on:
#      - mongodb
#    ports:
#      - 8082:8082
#    expose:
#      - 8082
#
#  user-service:
#    build: ./user-service
#    restart: always
#    container_name: user
#    depends_on:
#      - mongodb
#    ports:
#      - 8089:8089
#    expose:
#      - 8089
#
#  zuul-service:
#    build: ./zuul-service
#    container_name: zuul
#    ports:
#      - 8082:8082
#    expose:
#      - 8082